# Generated by Django 3.1 on 2020-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Time')),
                ('cor', models.CharField(max_length=200, verbose_name='Cor predominante')),
                ('fabricante', models.CharField(max_length=200, verbose_name='Fabricante')),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chuteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=200, verbose_name='Cor predominante')),
                ('fabricante', models.CharField(max_length=200, verbose_name='Fabricante')),
                ('tipo', models.CharField(choices=[('Campo', 'Campo'), ('Society', 'Society'), ('Salão', 'Salão')], max_length=10, verbose_name='Tipo')),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
